from .rust import (
    STRIP_WHITESPACE_RUST_DO_NOT_MINIFY_DOCTYPE,
    STRIP_WHITESPACE_RUST_ENSURE_SPEC_CONPLIANT_UNQUOTED_ATTRIBUTE_VALUES,
    STRIP_WHITESPACE_RUST_KEEP_CLOSING_TAGS,
    STRIP_WHITESPACE_RUST_KEEP_COMMENTS,
    STRIP_WHITESPACE_RUST_KEEP_HTML_AND_HEAD_OPENING_TAGS,
    STRIP_WHITESPACE_RUST_KEEP_SPACES_BETWEEN_ATTRIBUTES,
    STRIP_WHITESPACE_RUST_MINIFY_CSS,
    STRIP_WHITESPACE_RUST_MINIFY_JS,
    STRIP_WHITESPACE_RUST_REMOVE_BANGS,
    STRIP_WHITESPACE_RUST_REMOVE_PROCESSING_INSTRUCTIONS,
)

from .python import (
    STRIP_WHITESPACE_PYTHON_REMOVE_COMMENTS,
    STRIP_WHITESPACE_PYTHON_CONDENSE_STYLE_FROM_HTML,
    STRIP_WHITESPACE_PYTHON_CONDENSE_SCRIPT_FROM_HTML,
    STRIP_WHITESPACE_PYTHON_CLEAN_UNNEEDED_HTML_TAGS,
    STRIP_WHITESPACE_PYTHON_CONDENSE_HTML_WHITESPACE,
    STRIP_WHITESPACE_PYTHON_UNQUOTE_HTML_ATTRIBUTES,
)

from .ignored_paths import STRIP_WHITESPACE_MINIFY_IGNORED_PATHS

from .nbsp_mangle_character import STRIP_WHITESPACE_NBSP_MANGLE_CHARACTER
